-- Revert geonames:add_tables from pg

BEGIN;
SET search_path TO :"schema";

DROP TABLE IF EXISTS geoname CASCADE;
DROP TABLE IF EXISTS alternatename CASCADE;
DROP TABLE IF EXISTS countryinfo CASCADE;
DROP TABLE IF EXISTS hierarchy CASCADE;
DROP TABLE IF EXISTS admin1_codes_ascii CASCADE;
DROP TABLE IF EXISTS admin2_codes CASCADE;
DROP TABLE IF EXISTS continentinfo CASCADE;
DROP TABLE IF EXISTS feature_codes CASCADE;
DROP TABLE IF EXISTS iso_language_codes CASCADE;
DROP TABLE IF EXISTS time_zones CASCADE;
DROP TABLE IF EXISTS postal_codes CASCADE;

COMMIT;
